language: ruby
rvm:
  - 2.0
  - 2.1
  - 2.2
  - ruby-head
  - jruby
  - jruby-head
  - rbx-2
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby
    - rvm: jruby-head
    - rvm: rbx-2
  fast_finish: true
bundler_args: --retry=3 --jobs=3 --without production
addons:
  code_climate:
    repo_token: 6a19929ed0a99137c10684ba06ca240aa176173a4ff878248db3ec5f7aecf726
script: bundle exec rspec spec
