language: ruby
rvm:
  - 2.1.3
  - 2.1.0
  - jruby-18mode
  - jruby-19mode
  - rbx-2
  - ruby-head
  - jruby-head
  - ree
bundler_args: --without production
addons:
  code_climate:
    repo_token: 6a19929ed0a99137c10684ba06ca240aa176173a4ff878248db3ec5f7aecf726